const Application = require("../models/Application");
const Job = require("../models/Job");
const fs = require("fs");
const path = require("path");

const uploadDir = path.join(__dirname, "..", "uploads"); // Define relative to controller

// @desc    Apply to a job with CV upload
// @route   POST /api/applications/:jobId
// @access  Protected (Applier)
exports.applyToJob = async (req, res) => {
  const { jobId } = req.params;

  if (!req.file) {
    return res.status(400).json({ message: "CV file is required" });
  }

  try {
    // Check if the job exists
    const job = await Job.findById(jobId);
    if (!job) {
      // If job doesn't exist, delete uploaded file to prevent orphans
      fs.unlink(req.file.path, (err) => {
        if (err) console.error("Error deleting orphaned file:", err);
      });
      return res.status(404).json({ message: "Job not found" });
    }

    // Check if user already applied to this job
    const existingApplication = await Application.findOne({
      jobId: jobId,
      applierId: req.user._id,
    });

    if (existingApplication) {
      fs.unlink(req.file.path, (err) => {
        if (err) console.error("Error deleting redundant file:", err);
      });
      return res
        .status(400)
        .json({ message: "You have already applied for this job" });
    }

    // Create application
    const application = new Application({
      jobId: jobId,
      applierId: req.user._id,
      cvUrl: req.file.filename, // Store only the filename generated by Multer
      status: "applied", // Default status
    });

    const createdApplication = await application.save();

    // Populate fields for response
    await createdApplication.populate("jobId", "title description");
    await createdApplication.populate("applierId", "name email");

    res.status(201).json(createdApplication);
  } catch (error) {
    console.error("Apply Job Error:", error);
    // If error occurs after file upload, delete the file
    if (req.file && req.file.path) {
      fs.unlink(req.file.path, (err) => {
        if (err)
          console.error("Error deleting file after failed application:", err);
      });
    }
    if (error.code === 11000) {
      // Duplicate key error (already applied)
      return res
        .status(400)
        .json({ message: "You have already applied for this job" });
    }
    res.status(500).json({ message: "Server Error applying for job" });
  }
};

// @desc    Get applications submitted by the logged-in applier
// @route   GET /api/applications/mine
// @access  Protected (Applier)
exports.getMyApplications = async (req, res) => {
  try {
    const applications = await Application.find({ applierId: req.user._id })
      .populate("jobId", "title description location") // Populate job details
      .sort({ createdAt: -1 }); // Sort by newest first

    res.json(applications);
  } catch (error) {
    console.error("Get My Applications Error:", error);
    res.status(500).json({ message: "Server Error" });
  }
};

// @desc    Update an application (only allows applier to update non-status fields, e.g., maybe CV?)
// @route   PUT /api/applications/:id
// @access  Protected (Applier who owns the application)
// Note: The requirement is vague. Appliers typically *don't* update applications after submitting.
// This endpoint might be more useful if they could, for instance, withdraw or update contact info (not modeled here).
// Let's assume they can update the CV for now.
exports.updateMyApplication = async (req, res) => {
  const { id } = req.params;
  // For this example, we only handle potential CV update via re-upload.
  // Requires form-data request with a new 'cv' file field.
  // You'd need to add the cvUpload middleware to the route definition for this specifically.

  try {
    const application = await Application.findById(id);

    if (!application) {
      return res.status(404).json({ message: "Application not found" });
    }

    // Authorization Check: Ensure the logged-in user is the applier
    if (application.applierId.toString() !== req.user._id.toString()) {
      return res
        .status(403)
        .json({ message: "User not authorized to update this application" });
    }

    // If a new CV is uploaded
    if (req.file) {
      // Delete the old CV file
      const oldCvPath = path.join(uploadDir, application.cvUrl);
      fs.unlink(oldCvPath, (err) => {
        if (err && err.code !== "ENOENT") {
          // Ignore if file doesn't exist
          console.error("Error deleting old CV:", err);
        }
      });

      // Update the cvUrl field
      application.cvUrl = req.file.filename;
    } else {
      // No file uploaded, maybe update other fields if allowed?
      return res
        .status(400)
        .json({ message: "No updates provided (e.g., no new CV uploaded)" });
    }

    // Cannot change status via this route
    application.status = application.status; // Ensure status remains unchanged

    const updatedApplication = await application.save();
    res.json(updatedApplication);
  } catch (error) {
    console.error("Update Application Error:", error);
    // If error during save after new file upload, attempt to delete new file
    if (req.file && req.file.path) {
      fs.unlink(req.file.path, (err) => {
        if (err)
          console.error("Error deleting new CV after failed update:", err);
      });
    }
    res.status(500).json({ message: "Server Error updating application" });
  }
};

// @desc    Get all applications for a specific job
// @route   GET /api/applications/job/:jobId
// @access  Protected (Employer who owns job, Admin)
exports.getApplicationsForJob = async (req, res) => {
  const { jobId } = req.params;

  try {
    const job = await Job.findById(jobId);
    if (!job) {
      return res.status(404).json({ message: "Job not found" });
    }

    // Authorization Check: User must be admin or the employer who created the job
    if (
      req.user.role !== "admin" &&
      job.createdBy.toString() !== req.user._id.toString()
    ) {
      return res.status(403).json({
        message: "User not authorized to view applications for this job",
      });
    }

    const applications = await Application.find({ jobId: jobId })
      .populate("applierId", "name email") // Populate applier details
      .sort({ createdAt: "asc" }); // Sort by oldest first

    res.json(applications);
  } catch (error) {
    console.error("Get Applications for Job Error:", error);
    if (error.kind === "ObjectId") {
      return res
        .status(404)
        .json({ message: "Job not found (Invalid ID format)" });
    }
    res.status(500).json({ message: "Server Error" });
  }
};

// @desc    Update the status of an application
// @route   PATCH /api/applications/:id/status
// @access  Protected (Employer who owns job, Admin)
exports.updateApplicationStatus = async (req, res) => {
  const { id } = req.params; // Application ID
  const { status } = req.body;

  // Validate status
  const allowedStatuses = ["selected", "rejected"];
  if (!status || !allowedStatuses.includes(status.toLowerCase())) {
    return res.status(400).json({
      message: `Invalid status. Must be one of: ${allowedStatuses.join(", ")}`,
    });
  }

  try {
    const application = await Application.findById(id).populate("jobId"); // Populate job to check ownership

    if (!application) {
      return res.status(404).json({ message: "Application not found" });
    }

    // Check if the associated job exists
    if (!application.jobId) {
      return res
        .status(404)
        .json({ message: "Associated job not found for this application" });
    }

    // Authorization Check: User must be admin or the employer who created the job
    if (
      req.user.role !== "admin" &&
      application.jobId.createdBy.toString() !== req.user._id.toString()
    ) {
      return res.status(403).json({
        message: "User not authorized to update status for this application",
      });
    }

    // Update status
    application.status = status.toLowerCase();
    const updatedApplication = await application.save();

    // Populate applier info for the response
    await updatedApplication.populate("applierId", "name email");

    res.json(updatedApplication);
  } catch (error) {
    console.error("Update Application Status Error:", error);
    if (error.kind === "ObjectId") {
      return res
        .status(404)
        .json({ message: "Application not found (Invalid ID format)" });
    }
    res.status(500).json({ message: "Server Error" });
  }
};

// @desc    Get the status of the current user's application for a specific job
// @route   GET /api/jobs/:jobId/application-status  (or /api/applications/status/:jobId)
// @access  Private (Applier)
exports.checkApplicationStatus = async (req, res, next) => {
  const jobId = req.params.jobId;
  const applierId = req.user._id; // Assuming protect middleware sets req.user

  // Validate inputs (basic)
  if (!jobId) {
    return next(new ErrorResponse(`Invalid Job ID: ${jobId}`, 400));
  }
  if (!applierId) {
    // Should be caught by 'protect' middleware, but good practice
    return next(new ErrorResponse(`User not authenticated`, 401));
  }

  // Find the application by jobId and applierId
  const application = await Application.findOne({
    jobId: jobId,
    applierId: applierId,
  })
    .select("status _id") // Select only the status and _id fields
    .lean(); // Use .lean() for faster read-only operations if not modifying

  // Check if application exists and return the appropriate structure
  if (application) {
    // Application found, return its status and ID
    res.status(200).json({
      success: true, // Optional: standard success flag
      application: {
        _id: application._id,
        status: application.status,
      },
    });
  } else {
    // No application found for this user and job
    res.status(200).json({
      success: true,
      application: null, // Frontend expects null if no application exists
    });
  }
};
